spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=UTF-8&nullCatalogMeansCurrent=true&serverTimezone=GMT&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true

activiti:
    check-process-definitions: false
    database-schema-update: true